trigger:
   branches:
     include:
       - main
stages:
- stage: Validate
  displayName: "Validate Bicep Templates"
  jobs:
  - job: BicepValidation
    displayName: "Run Bicep What-if"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "🔎 Validating Bicep Deployment..."
                az bicep version

                Write-Host "📦 Running What-If Analysis..."
                az deployment sub what-if `
                  --location westeurope `
                  --template-file ./main.bicep `
                  --parameters @main.parameters.json
        displayName: 'Bicep What-if Validation'
          
        
    