trigger:
   branches:
     include:
       - main
stages:
- stage: Validate
  displayName: "Validate Bicep Templates"
  jobs:
  - job: BicepValidation
    displayName: "Run Bicep Lint + What-if"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Lint Bicep Template'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "🔍 Linting Bicep..."
            bicep build ./main.bicep

      - task: AzureCLI@2
        displayName: 'Bicep What-if Validation'
        inputs:
           azureSubscription: 'azure-rg-web-bicep'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
            echo "🔍 Validating Bicep Deployment..."
            az bicep version

            echo "📦 Running What-If Analysis..."
            az deployment group what-if \
              --resource-group rg-webapp-infra-dev \
              --template-file ./main.bicep \
              --parameters main.parameters.json
        
          
- stage: Deploy
  displayName: "Manual Approval Deploy"
  dependsOn: Validate
  condition: succeeded()
  jobs:
    - deployment: DeployInfra
      displayName: "Deploy to Azure (Manual Approval Required)"
      environment: 'Production'
      strategy: 
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'azure-rg-web-bicep'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "🚀 Deploying Bicep Template..."
                    az deployment group create \
                      --resource-group rg-webapp-infra-dev \
                      --template-file ./main.bicep \
                      --parameters @main.parameters.json
                displayName: 'Deploy Bicep Template'